@startuml
title Sequence Diagram: Add New Client

actor "Financial Advisor" as User
participant UI as ":UI"
participant Parser as ":Parser"
participant Command as ":AddCommand"
participant ClientList as ":ClientList"
participant Client as ":Client"

User -> UI: enters "client add n/John Doe ..."
activate UI

ref over UI, Parser
    **Command Parsing Sequence**
    (Details on how the input string is converted
    into a Command object are omitted for brevity.
    See the "Command Parsing" diagram for details.)
end ref

note right of UI: The UI now holds an AddCommand object.

UI-> Command : execute()
activate Command

Command -> ClientList: addItem(arguments, policyList)
activate ClientList

ClientList -> Client**: create(arguments, policyList)
activate Client
note left of Client: The Client constructor parses the details\n(name, nric, etc.) and validates them.
Client -> Client: Client();
activate Client
Client --> Client
deactivate Client
Client -->ClientList
deactivate Client

ClientList -> ClientList: addClient(client)
activate ClientList
ClientList --> ClientList
deactivate ClientList

ClientList --> Command
deactivate ClientList

Command --> UI
deactivate Command

UI -> Command : printExecutionMessage()
activate Command
Command --> UI: "Noted. I've added this client: ..."
deactivate Command

UI --> User: Displays success message
deactivate UI

@enduml