
@startuml
title Sequence Diagram: Application Startup Data Loading

actor User as "System Launch"
participant FinanceProPlus
participant StorageManager
participant PolicyList
participant ClientList
participant UserList
participant MeetingList
participant ArchivedClientList
participant TaskList
participant Logger


== Initialization ==

User -> FinanceProPlus: start application
activate FinanceProPlus

FinanceProPlus -> StorageManager: new StorageManager()
activate StorageManager
StorageManager --> StorageManager: createFolder("data/")\ncreateFolder("exports/")\ncreateFolder("data/client_tasks")
activate StorageManager
StorageManager --> StorageManager
deactivate StorageManager
StorageManager --> FinanceProPlus
deactivate StorageManager

== Data Loading ==

FinanceProPlus -> StorageManager: loadFromFile("policy.txt")
activate StorageManager
StorageManager --> FinanceProPlus: List<String> policyData
deactivate StorageManager
FinanceProPlus -> PolicyList: loadFromStorage(policyData)
activate PolicyList
PolicyList --> FinanceProPlus:
deactivate PolicyList

FinanceProPlus -> StorageManager: loadFromFile("client.txt")
activate StorageManager
StorageManager --> FinanceProPlus: List<String> clientData
deactivate StorageManager
FinanceProPlus -> ClientList: loadFromStorage(clientData, policies)
activate ClientList
ClientList --> FinanceProPlus:
deactivate ClientList

FinanceProPlus -> StorageManager: loadFromFile("user.txt")
activate StorageManager
StorageManager --> FinanceProPlus: List<String> userData
deactivate StorageManager
FinanceProPlus -> UserList: loadFromStorage(userData)
activate UserList
UserList --> FinanceProPlus:
deactivate UserList

FinanceProPlus -> StorageManager: loadFromFile("meeting.txt")
activate StorageManager
StorageManager --> FinanceProPlus: List<String> meetingData
deactivate StorageManager
FinanceProPlus -> MeetingList: loadFromStorage(meetingData)
activate MeetingList
MeetingList --> FinanceProPlus:
deactivate MeetingList

FinanceProPlus -> StorageManager: loadFromFile("archived_clients.txt")
activate StorageManager
StorageManager --> FinanceProPlus: List<String> archivedClientData
deactivate StorageManager
FinanceProPlus -> ArchivedClientList: loadFromStorage(archivedClientData)
activate ArchivedClientList
ArchivedClientList --> FinanceProPlus:
deactivate ArchivedClientList

FinanceProPlus -> StorageManager: loadFromFile("task.txt")
activate StorageManager
StorageManager --> FinanceProPlus: List<String> taskData
deactivate StorageManager
FinanceProPlus ->TaskList: loadFromStorage(archivedClientData)
activate TaskList
TaskList --> FinanceProPlus:
deactivate TaskList

FinanceProPlus -> Logger: info("Data loaded successfully.")
deactivate FinanceProPlus

@enduml