@startuml
title Sequence Diagram: Autosave Triggered by FinanceProPlus (with Logging & Archived Clients)

actor User
participant "UI" as UI
participant "FinanceProPlus" as App
participant "Parser" as Parser
participant "Command" as Command
participant "StorageManager" as Storage
participant "Logger" as Logger

User -> UI: enters command
activate UI

UI -> App: readCommand()
activate App

App -> Parser: parse()
activate Parser
Parser --> App: Command object
deactivate Parser
App -->UI
UI -> Command: execute()
activate Command
Command -> Command: ... (internal logic not shown)
activate Command
Command --> Command
deactivate Command
Command --> UI
deactivate Command




UI -> Command: printExecutionMessage()
activate Command
Command --> UI
deactivate Command

UI --> User: displays success message
deactivate UI

== Autosave triggered ==

App -> Storage: saveToFile()
activate Storage
Storage --> App:
deactivate Storage

App -> Storage: exportToCSV()
activate Storage
Storage --> App:
deactivate Storage

App -> Logger: info("Data saved successfully")
activate Logger
Logger --> App
deactivate Logger

deactivate App
@enduml



