@startuml


title Sequence Diagram: Add New Task


actor User as "Financial Advisor"
participant ": UI" as UI
participant ": FinanceProPlus" as App
participant ": Parser" as Parser
participant ": TaskParser" as TaskParser
participant ": AddCommand" as Command
participant ": LookUpTable" as LookUpTable
participant ": TaskList" as TaskList
participant ": Task" as Task
participant ": Console" as Console


User -> UI: enters "task add d/Report by/15-01-2024"
activate UI
App -> UI: readCommand()
activate App
activate UI
UI --> App: "task add d/Report by/15-01-2024"
deactivate UI

ref over App, Parser, TaskParser
    **Generic Parsing Sequence**
    (Details on how the input string is converted
    into a Command object are omitted for brevity.
    See the "Generic Parser Sequence" diagram for details.)
end ref

note right of App: The App now holds an AddCommand object.

App -> Command: execute(lookUpTable)
    activate Command
    Command -> LookUpTable: getList("task")
    activate LookUpTable
    LookUpTable --> Command: TaskList
    deactivate LookUpTable
    Command -> TaskList: addItem(arguments)
    activate TaskList

    TaskList -> Task**: new Task(arguments)
    activate Task

    Task -> Task: Task()
    activate Task
    Task --> Task
    deactivate Task
    Task --> TaskList
    deactivate Task
    TaskList -> TaskList: tasks.add(task)
    activate TaskList
    TaskList --> TaskList
    deactivate TaskList
    TaskList --> TaskList
    deactivate TaskList
    TaskList -> Console: print "Noted. I've added this task:"
    TaskList -> Console: print task.toString()
    TaskList --> Command
    deactivate TaskList
    Command --> App
    deactivate Command
    App -> Command: printExecutionMessage()
    Activate Command
    Command -> Console: print "Added successfully!"
    Command --> App
    deactivate Command


    Console --> User: Shows console output

deactivate App
deactivate UI

@enduml

